# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0002_auto_20180424_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emai',
            new_name='email',
        ),
    ]
