# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0002_auto_20180419_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
