# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0003_auto_20180420_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lname',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='temp', max_length=35),
            preserve_default=False,
        ),
    ]
