# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0004_auto_20180422_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='temp', max_length=35),
            preserve_default=False,
        ),
    ]
